# Generated by Django 5.2 on 2025-05-17 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Especie_Mascota',
            fields=[
                ('id', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField(max_length=10)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.dueño')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mascotas.especie_mascota')),
            ],
        ),
    ]
