# Generated by Django 5.2 on 2025-05-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('rut', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Especie_Mascota',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_especie', models.CharField(max_length=50)),
                ('fecha_nac', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
