# Generated by Django 5.2 on 2025-05-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre_especie',
            new_name='nombre_mascota',
        ),
    ]
