# Generated by Django 5.2 on 2025-05-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0002_rename_nombre_especie_mascota_nombre_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
