# Generated by Django 5.2 on 2025-05-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0003_alter_dueño_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nac',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
    ]
