# Generated by Django 5.2 on 2025-05-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0004_alter_mascota_fecha_nac_alter_mascota_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie_mascota',
            name='id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
